const state={session:localStorage.getItem("gpv_rh_session")||"",user:null,jobs:[],applications:[]};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const titles={dashboard:"Visão geral",jobs:"Gestão de vagas",applications:"Candidaturas"};
document.addEventListener("DOMContentLoaded",init);
async function init(){bind();if(!state.session)return showLogin();try{const r=await get("adminMe");state.user=r.data;showApp();await refresh()}catch{clearSession();showLogin()}}
function bind(){
  $("#loginForm").addEventListener("submit",login);$("#logoutButton").addEventListener("click",logout);$("#mobileMenu").addEventListener("click",()=>$("#sidebar").classList.toggle("open"));
  $$('[data-view]').forEach(x=>x.addEventListener("click",e=>{e.preventDefault();setView(x.dataset.view)}));$$('[data-close-modal]').forEach(x=>x.addEventListener("click",()=>x.closest("dialog").close()));
  $("#newJobButton").addEventListener("click",()=>openJob());$("#dashboardNewJob").addEventListener("click",()=>openJob());$("#jobForm").addEventListener("submit",saveJob);$("#applicationStatusForm").addEventListener("submit",saveApplication);
  $("#jobAdminSearch").addEventListener("input",renderJobs);$("#jobStatusFilter").addEventListener("change",renderJobs);$("#applicationSearch").addEventListener("input",renderApplications);$("#applicationJobFilter").addEventListener("change",renderApplications);$("#applicationStatusFilter").addEventListener("change",renderApplications)
}
async function login(e){e.preventDefault();const b=$("#loginButton"),m=$("#loginMessage");m.textContent="";b.disabled=true;b.textContent="Entrando...";try{const r=await post({action:"adminLogin",email:$("#loginEmail").value.trim(),password:$("#loginPassword").value},false);state.session=r.data.session;state.user=r.data.user;localStorage.setItem("gpv_rh_session",state.session);showApp();await refresh()}catch(err){m.textContent=err.message}finally{b.disabled=false;b.textContent="Entrar"}}
async function logout(){try{await post({action:"adminLogout"})}catch{}clearSession();showLogin()}
function clearSession(){state.session="";state.user=null;localStorage.removeItem("gpv_rh_session")}
function showLogin(){$("#loginScreen").classList.remove("hidden");$("#appShell").classList.add("hidden")}
function showApp(){$("#loginScreen").classList.add("hidden");$("#appShell").classList.remove("hidden");const n=state.user?.nome||"Gestão RH";$("#sidebarUserName").textContent=n;$("#sidebarUserRole").textContent=state.user?.perfil==="ADMIN"?"Administrador":"Gestor RH";$("#sidebarAvatar").textContent=initials(n)}
async function refresh(){await Promise.all([loadDashboard(),loadJobs(),loadApplications()])}
async function loadDashboard(){const r=await get("adminDashboard"),d=r.data;$("#kpiActiveJobs").textContent=d.activeJobs||0;$("#kpiApplications").textContent=d.totalApplications||0;$("#kpiAnalysis").textContent=d.inAnalysis||0;$("#kpiInterviews").textContent=d.interviews||0;const c=$("#recentApplications"),arr=d.recentApplications||[];c.innerHTML=arr.length?arr.map(i=>`<div class="compact-row"><div><strong>${esc(i.NOME||"Candidato")}</strong><span>${esc(i.EMAIL||"")}</span></div><div><strong>${esc(i.VAGA_TITULO||"Banco de Talentos")}</strong><span>${esc(i.DATA_ENVIO||"")}</span></div><div>${badge(i.STATUS||"RECEBIDA")}</div></div>`).join(""):`<div class="empty-state">Nenhuma candidatura recebida ainda.</div>`}
async function loadJobs(){const r=await get("adminListJobs");state.jobs=Array.isArray(r.data)?r.data:[];populateJobFilter();renderJobs()}
async function loadApplications(){const r=await get("adminListApplications");state.applications=Array.isArray(r.data)?r.data:[];populateJobFilter();renderApplications()}
function setView(v){if(!titles[v])return;$$('.view').forEach(x=>x.classList.remove("active"));$(`#view-${v}`).classList.add("active");$$('.nav-item').forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#pageTitle").textContent=titles[v];$("#sidebar").classList.remove("open")}
function renderJobs(){const q=norm($("#jobAdminSearch").value),s=$("#jobStatusFilter").value;const arr=state.jobs.filter(j=>(!q||norm(`${j.TITULO} ${j.SETOR} ${j.CIDADE} ${j.UF}`).includes(q))&&(!s||String(j.STATUS||"").toUpperCase()===s));$("#jobsAdminCount").textContent=`${arr.length} registro(s)`;$("#jobsTableBody").innerHTML=arr.length?arr.map(j=>`<tr><td><span class="table-title">${esc(j.TITULO||"")}</span><span class="table-subtitle">${esc(j.SETOR||"")}</span></td><td>${esc([j.CIDADE,j.UF].filter(Boolean).join(" - "))}</td><td>${esc(j.MODALIDADE||"—")}</td><td>${badge(j.STATUS||"RASCUNHO")}</td><td>${esc(j.DATA_PUBLICACAO||"—")}</td><td><button class="table-action" data-edit-job="${esc(j.ID)}">Editar</button></td></tr>`).join(""):`<tr><td colspan="6"><div class="empty-state">Nenhuma vaga encontrada.</div></td></tr>`;$$('[data-edit-job]').forEach(b=>b.addEventListener("click",()=>openJob(state.jobs.find(j=>String(j.ID)===b.dataset.editJob))))}
function openJob(j=null){$("#jobModalTitle").textContent=j?"Editar vaga":"Nova vaga";const map={jobId:j?.ID||"",jobTitle:j?.TITULO||"",jobSector:j?.SETOR||"",jobQuantity:j?.QUANTIDADE_VAGAS||1,jobCity:j?.CIDADE||"",jobUf:j?.UF||"",jobModality:j?.MODALIDADE||"Presencial",jobContract:j?.CONTRATO||"",jobJourney:j?.JORNADA||"",jobStatus:j?.STATUS||"RASCUNHO",jobAbout:j?.SOBRE_EMPRESA||"",jobResponsibilities:multi(j?.RESPONSABILIDADES||""),jobRequirements:multi(j?.REQUISITOS||""),jobDifferentials:multi(j?.DIFERENCIAIS||"")};Object.entries(map).forEach(([k,v])=>$("#"+k).value=v);$("#jobFormMessage").textContent="";$("#jobModal").showModal()}
async function saveJob(e){e.preventDefault();const b=$("#saveJobButton"),m=$("#jobFormMessage");m.textContent="";b.disabled=true;b.textContent="Salvando...";try{await post({action:"adminSaveJob",job:{ID:v("jobId"),TITULO:v("jobTitle"),SETOR:v("jobSector"),CIDADE:v("jobCity"),UF:v("jobUf").toUpperCase(),MODALIDADE:v("jobModality"),CONTRATO:v("jobContract"),JORNADA:v("jobJourney"),QUANTIDADE_VAGAS:Number(v("jobQuantity")||1),SOBRE_EMPRESA:v("jobAbout"),RESPONSABILIDADES:v("jobResponsibilities"),REQUISITOS:v("jobRequirements"),DIFERENCIAIS:v("jobDifferentials"),STATUS:v("jobStatus")}});$("#jobModal").close();toast("Vaga salva com sucesso.");await Promise.all([loadJobs(),loadDashboard()])}catch(err){m.textContent=err.message}finally{b.disabled=false;b.textContent="Salvar vaga"}}
function renderApplications(){const q=norm($("#applicationSearch").value),job=$("#applicationJobFilter").value,s=$("#applicationStatusFilter").value;const arr=state.applications.filter(i=>(!q||norm(`${i.NOME} ${i.EMAIL} ${i.PROTOCOLO} ${i.VAGA_TITULO}`).includes(q))&&(!job||i.VAGA_TITULO===job)&&(!s||String(i.STATUS||"").toUpperCase()===s));$("#applicationsCount").textContent=`${arr.length} registro(s)`;$("#applicationsTableBody").innerHTML=arr.length?arr.map(i=>`<tr><td><span class="table-title">${esc(i.NOME||"")}</span><span class="table-subtitle">${esc(i.EMAIL||"")}</span></td><td>${esc(i.VAGA_TITULO||"Banco de Talentos")}</td><td>${esc(i.DATA_ENVIO||"—")}</td><td>${badge(i.STATUS||"RECEBIDA")}</td><td><button class="table-action" data-app="${esc(i.ID)}">Ver ficha</button></td></tr>`).join(""):`<tr><td colspan="5"><div class="empty-state">Nenhuma candidatura encontrada.</div></td></tr>`;$$('[data-app]').forEach(b=>b.addEventListener("click",()=>openApplication(state.applications.find(i=>String(i.ID)===b.dataset.app))))}
function openApplication(i){$("#candidateId").value=i.ID||"";$("#candidateName").textContent=i.NOME||"Candidato";$("#candidateJob").textContent=i.VAGA_TITULO||"Banco de Talentos";$("#candidateAvatar").textContent=initials(i.NOME||"C");$("#candidateEmail").textContent=i.EMAIL||"—";$("#candidatePhone").textContent=i.TELEFONE||"—";$("#candidateLocation").textContent=[i.CIDADE,i.UF].filter(Boolean).join(" - ")||"—";$("#candidateProtocol").textContent=i.PROTOCOLO||"—";$("#candidatePresentation").textContent=i.APRESENTACAO||"Nenhuma apresentação informada.";$("#candidateStatus").value=i.STATUS||"RECEBIDA";$("#candidateNotes").value=i.OBSERVACAO_INTERNA||"";setLink("#candidateResume",i.CURRICULO_URL);setLink("#candidateLinkedin",i.LINKEDIN);setLink("#candidatePortfolio",i.PORTFOLIO);$("#candidateFormMessage").textContent="";$("#applicationModal").showModal()}
async function saveApplication(e){e.preventDefault();const b=$("#saveApplicationStatus"),m=$("#candidateFormMessage");b.disabled=true;b.textContent="Salvando...";m.textContent="";try{await post({action:"adminUpdateApplicationStatus",applicationId:v("candidateId"),status:v("candidateStatus"),notes:v("candidateNotes")});$("#applicationModal").close();toast("Candidatura atualizada.");await Promise.all([loadApplications(),loadDashboard()])}catch(err){m.textContent=err.message}finally{b.disabled=false;b.textContent="Salvar atualização"}}
function populateJobFilter(){const sel=$("#applicationJobFilter"),cur=sel.value;const arr=[...new Set(state.applications.map(i=>i.VAGA_TITULO).concat(state.jobs.map(j=>j.TITULO)).filter(Boolean))].sort();sel.innerHTML='<option value="">Todas as vagas</option>'+arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");if(arr.includes(cur))sel.value=cur}
async function get(action,params={}){const q=new URLSearchParams({action,...params});if(state.session)q.set("session",state.session);return request(`/api/proxy?${q}`)}
async function post(payload,withSession=true){const body={...payload};if(withSession&&state.session)body.session=state.session;return request("/api/proxy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})}
async function request(url,opt={}){const r=await fetch(url,opt),p=await r.json().catch(()=>({}));if(r.status===401||p.code==="SESSION_EXPIRED"){clearSession();showLogin()}if(!r.ok||p.ok===false)throw new Error(p.error||"Não foi possível concluir a solicitação.");return p}
function badge(s){const v1=String(s||"").trim().toUpperCase(),c=norm(v1).replace(/\s+/g,"-");return `<span class="status-badge status-${c}">${esc(friendly(v1))}</span>`}
function friendly(s){return {ATIVA:"Ativa",RASCUNHO:"Rascunho",PAUSADA:"Pausada",ENCERRADA:"Encerrada",RECEBIDA:"Recebida","EM ANÁLISE":"Em análise",ENTREVISTA:"Entrevista",APROVADO:"Aprovado","NÃO SELECIONADO":"Não selecionado","BANCO DE TALENTOS":"Banco de talentos"}[s]||s}
function setLink(sel,url){const e=$(sel);if(url){e.href=url;e.classList.remove("disabled")}else{e.removeAttribute("href");e.classList.add("disabled")}}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2500)}
function multi(x){return String(x||"").replace(/;\s*/g,"\n")}function initials(n){return String(n||"RH").trim().split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase()}function v(id){return $("#"+id)?.value?.trim()||""}function norm(x){return String(x||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim()}function esc(x){return String(x??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
